[build]
  command = "pip install -r requirements.txt"
  publish = "public"

[functions]
  directory = "netlify/functions"
  included_files = ["app/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
